#include "AppConfig.h"
#include "builtin/I18nLoader.h"
#include "common/i18n/Language.h"
#include "common/log/log.hpp"
#include "common/log/LogRingBuffer.h"
#include "domain/interface/BesqContext.h"
#include "domain/interface/web/WebModule.h"
#include "domain/interface/web/http/HttpServer.h"
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <map>
#include <memory>
#include <string>
#include <string_view>

namespace besq::data {
// Embedded frontend assets (generated by embed_resource).
std::string_view frontend_index_html();
std::string_view frontend_styles_css();
std::string_view frontend_app_js();
std::string_view frontend_api_js();
std::string_view frontend_i18n_js();
std::string_view frontend_view_calculator();
std::string_view frontend_view_profiles();
std::string_view frontend_view_algorithms();
std::string_view frontend_view_logs();
std::string_view frontend_view_settings();
std::string_view frontend_view_status();
} // namespace besq::data

static std::string read_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    return std::string((std::istreambuf_iterator<char>(f)),
                       std::istreambuf_iterator<char>());
}

/// Served frontend assets: URL → content type + embedded-symbol accessor.
/// MUST stay in sync with the embed_resource loops in CMakeLists.txt.
struct Asset { const char* url; const char* type; std::string_view (*embed)(); };
static constexpr Asset kAssets[] = {
    {"/index.html", "text/html", besq::data::frontend_index_html},
    {"/styles.css", "text/css",  besq::data::frontend_styles_css},
    {"/app.js",     "text/javascript", besq::data::frontend_app_js},
    {"/api.js",     "text/javascript", besq::data::frontend_api_js},
    {"/i18n.js",    "text/javascript", besq::data::frontend_i18n_js},
    {"/views/calculator.js", "text/javascript", besq::data::frontend_view_calculator},
    {"/views/profiles.js",   "text/javascript", besq::data::frontend_view_profiles},
    {"/views/algorithms.js", "text/javascript", besq::data::frontend_view_algorithms},
    {"/views/logs.js",       "text/javascript", besq::data::frontend_view_logs},
    {"/views/settings.js",   "text/javascript", besq::data::frontend_view_settings},
    {"/views/status.js",     "text/javascript", besq::data::frontend_view_status},
};

/// Build the static-resource table. When `frontend_dir` is non-empty (dev
/// mode --frontend-dir), read files from disk for hot reload; otherwise use
/// the embedded copies.
static std::map<std::string, webhttp::StaticResource> build_static(const std::string& frontend_dir) {
    using webhttp::StaticResource;
    std::map<std::string, StaticResource> m;
    for (const auto& a : kAssets) {
        if (!frontend_dir.empty()) {
            auto disk = std::filesystem::path(frontend_dir) / std::string(a.url).substr(1);
            if (std::filesystem::exists(disk)) {
                m[a.url] = StaticResource{a.type, read_file(disk.string())};
                continue;
            }
        }
        m[a.url] = StaticResource{a.type, std::string(a.embed())};
    }
    return m;
}

int main(int argc, char* argv[]) try {
    auto& cfg = AppConfig::get();
    register_builtin_translations(LanguageManager::instance());
    setup_logger(cfg.logger_config());

    bool open_browser = cfg.gui_open_browser;
    std::string frontend_dir;   // --frontend-dir (dev hot reload)
    for (int i = 1; i < argc; ++i) {
        if (std::string(argv[i]) == "--browser") open_browser = true;
        else if (std::string(argv[i]) == "--frontend-dir" && i + 1 < argc)
            frontend_dir = argv[++i];
    }

    BesqContext ctx;
    ctx.load_builtin();
    ctx.load_profiles();

    // Ring buffer for /api/logs.
    auto ring = std::make_shared<LogRingBuffer>(1024);
    Logger::instance().set_ring_buffer(ring);

    webhttp::WebModule module(ctx);
    module.set_static_resources(build_static(frontend_dir));

    // WebModule does all routing (/health, /api/*, static assets); the HTTP
    // server just bridges bytes ↔ dispatch. Same wiring as test_web_integration.
    // Dispatch DIRECTLY — re-wrapping with HttpResponse::json would force
    // content_type application/json and break the SPA's text/html assets.
    webhttp::HttpServer server;
    server.set_fallback([&](const webhttp::HttpRequest& r) {
        return module.dispatch(r.method, r.path, r.body);
    });

    if (!server.start(cfg.gui_host, cfg.gui_port)) {
        std::cerr << "besq-gui: failed to bind " << cfg.gui_host << ":" << cfg.gui_port << "\n";
        return 1;
    }

    const auto url = "http://" + cfg.gui_host + ":" + std::to_string(server.port()) + "/";
    std::cout << "besq-gui serving at " << url << "\n";

    // v1 host: the default browser. A native WebView2 window (src/gui/
    // webview_host.*) is future work — it needs the Microsoft WebView2 SDK,
    // which is not vendored. `server.run()` keeps serving on this thread for
    // the process lifetime; Ctrl+C exits.
    if (open_browser) {
#ifdef _WIN32
        std::string cmd = "start \"\" \"" + url + "\"";
        std::system(cmd.c_str());
#else
        std::string cmd = "xdg-open " + url + " >/dev/null 2>&1 &";
        std::system(cmd.c_str());
#endif
    }

    server.run();
    return 0;

} catch (const std::exception& e) {
    std::cerr << "besq-gui: " << e.what() << std::endl;
    return 1;
}
