#include "AppConfig.h"
#include "BuildConfig.h"
#include "builtin/I18nLoader.h"
#include "common/i18n/Language.h"
#include "common/log/log.hpp"
#include "domain/interface/BesqContext.h"
#include "domain/interface/components/http/HttpServer.h"
#include "domain/interface/components/http/RateLimiter.h"
#include "domain/interface/web/WebModule.h"
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <map>
#include <memory>
#include <string>
#include <string_view>

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#else
#include <unistd.h>
#endif

namespace besq::data {
// Embedded frontend assets (generated by embed_resource).
std::string_view frontend_index_html();
std::string_view frontend_styles_css();
std::string_view frontend_app_js();
std::string_view frontend_api_js();
std::string_view frontend_i18n_js();
std::string_view frontend_names_zh_js();
std::string_view frontend_sprite_js();
std::string_view frontend_vendor_icons_bow_png();
std::string_view frontend_vendor_icons_brush_png();
std::string_view frontend_vendor_icons_carrot_on_a_stick_png();
std::string_view frontend_vendor_icons_chainmail_boots_png();
std::string_view frontend_vendor_icons_chainmail_chestplate_png();
std::string_view frontend_vendor_icons_chainmail_helmet_png();
std::string_view frontend_vendor_icons_chainmail_leggings_png();
std::string_view frontend_vendor_icons_copper_axe_png();
std::string_view frontend_vendor_icons_copper_boots_png();
std::string_view frontend_vendor_icons_copper_chestplate_png();
std::string_view frontend_vendor_icons_copper_helmet_png();
std::string_view frontend_vendor_icons_copper_hoe_png();
std::string_view frontend_vendor_icons_copper_leggings_png();
std::string_view frontend_vendor_icons_copper_pickaxe_png();
std::string_view frontend_vendor_icons_copper_shovel_png();
std::string_view frontend_vendor_icons_copper_spear_png();
std::string_view frontend_vendor_icons_copper_sword_png();
std::string_view frontend_vendor_icons_crossbow_png();
std::string_view frontend_vendor_icons_diamond_axe_png();
std::string_view frontend_vendor_icons_diamond_boots_png();
std::string_view frontend_vendor_icons_diamond_chestplate_png();
std::string_view frontend_vendor_icons_diamond_helmet_png();
std::string_view frontend_vendor_icons_diamond_hoe_png();
std::string_view frontend_vendor_icons_diamond_leggings_png();
std::string_view frontend_vendor_icons_diamond_pickaxe_png();
std::string_view frontend_vendor_icons_diamond_shovel_png();
std::string_view frontend_vendor_icons_diamond_spear_png();
std::string_view frontend_vendor_icons_diamond_sword_png();
std::string_view frontend_vendor_icons_elytra_png();
std::string_view frontend_vendor_icons_enchanted_book_png();
std::string_view frontend_vendor_icons_fishing_rod_png();
std::string_view frontend_vendor_icons_flint_and_steel_png();
std::string_view frontend_vendor_icons_golden_axe_png();
std::string_view frontend_vendor_icons_golden_boots_png();
std::string_view frontend_vendor_icons_golden_chestplate_png();
std::string_view frontend_vendor_icons_golden_helmet_png();
std::string_view frontend_vendor_icons_golden_hoe_png();
std::string_view frontend_vendor_icons_golden_leggings_png();
std::string_view frontend_vendor_icons_golden_pickaxe_png();
std::string_view frontend_vendor_icons_golden_shovel_png();
std::string_view frontend_vendor_icons_golden_spear_png();
std::string_view frontend_vendor_icons_golden_sword_png();
std::string_view frontend_vendor_icons_iron_axe_png();
std::string_view frontend_vendor_icons_iron_boots_png();
std::string_view frontend_vendor_icons_iron_chestplate_png();
std::string_view frontend_vendor_icons_iron_helmet_png();
std::string_view frontend_vendor_icons_iron_hoe_png();
std::string_view frontend_vendor_icons_iron_leggings_png();
std::string_view frontend_vendor_icons_iron_pickaxe_png();
std::string_view frontend_vendor_icons_iron_shovel_png();
std::string_view frontend_vendor_icons_iron_spear_png();
std::string_view frontend_vendor_icons_iron_sword_png();
std::string_view frontend_vendor_icons_leather_boots_png();
std::string_view frontend_vendor_icons_leather_chestplate_png();
std::string_view frontend_vendor_icons_leather_helmet_png();
std::string_view frontend_vendor_icons_leather_leggings_png();
std::string_view frontend_vendor_icons_mace_png();
std::string_view frontend_vendor_icons_misc_png();
std::string_view frontend_vendor_icons_netherite_axe_png();
std::string_view frontend_vendor_icons_netherite_boots_png();
std::string_view frontend_vendor_icons_netherite_chestplate_png();
std::string_view frontend_vendor_icons_netherite_helmet_png();
std::string_view frontend_vendor_icons_netherite_hoe_png();
std::string_view frontend_vendor_icons_netherite_leggings_png();
std::string_view frontend_vendor_icons_netherite_pickaxe_png();
std::string_view frontend_vendor_icons_netherite_shovel_png();
std::string_view frontend_vendor_icons_netherite_spear_png();
std::string_view frontend_vendor_icons_netherite_sword_png();
std::string_view frontend_vendor_icons_shears_png();
std::string_view frontend_vendor_icons_shield_png();
std::string_view frontend_vendor_icons_stone_axe_png();
std::string_view frontend_vendor_icons_stone_hoe_png();
std::string_view frontend_vendor_icons_stone_pickaxe_png();
std::string_view frontend_vendor_icons_stone_shovel_png();
std::string_view frontend_vendor_icons_stone_spear_png();
std::string_view frontend_vendor_icons_stone_sword_png();
std::string_view frontend_vendor_icons_trident_png();
std::string_view frontend_vendor_icons_turtle_helmet_png();
std::string_view frontend_vendor_icons_turtle_shell_png();
std::string_view frontend_vendor_icons_warped_fungus_on_a_stick_png();
std::string_view frontend_vendor_icons_wooden_axe_png();
std::string_view frontend_vendor_icons_wooden_hoe_png();
std::string_view frontend_vendor_icons_wooden_pickaxe_png();
std::string_view frontend_vendor_icons_wooden_shovel_png();
std::string_view frontend_vendor_icons_wooden_spear_png();
std::string_view frontend_vendor_icons_wooden_sword_png();
std::string_view frontend_vendor_icons_sprite_png();
std::string_view frontend_vendor_mdui_mdui_css();
std::string_view frontend_vendor_mdui_mdui_global_js();
std::string_view frontend_view_calculator();
std::string_view frontend_view_profiles();
std::string_view frontend_view_algorithms();
std::string_view frontend_view_history();
std::string_view frontend_view_settings();
std::string_view frontend_view_status();
std::string_view frontend_view_pager();
} // namespace besq::data

static std::string read_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    return std::string((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
}

/// Served frontend assets: URL → content type + embedded-symbol accessor.
/// MUST stay in sync with the embed_resource loops in CMakeLists.txt.
struct Asset {
    const char* url;
    const char* type;
    std::string_view (*embed)();
};
static constexpr Asset kAssets[] = {
    {"/index.html", "text/html", besq::data::frontend_index_html},
    {"/styles.css", "text/css", besq::data::frontend_styles_css},
    {"/app.js", "text/javascript", besq::data::frontend_app_js},
    {"/api.js", "text/javascript", besq::data::frontend_api_js},
    {"/i18n.js", "text/javascript", besq::data::frontend_i18n_js},
    {"/names_zh.js", "text/javascript", besq::data::frontend_names_zh_js},
    {"/sprite.js", "text/javascript", besq::data::frontend_sprite_js},
    {"/vendor/icons/bow.png", "image/png", besq::data::frontend_vendor_icons_bow_png},
    {"/vendor/icons/brush.png", "image/png", besq::data::frontend_vendor_icons_brush_png},
    {"/vendor/icons/carrot_on_a_stick.png", "image/png", besq::data::frontend_vendor_icons_carrot_on_a_stick_png},
    {"/vendor/icons/chainmail_boots.png", "image/png", besq::data::frontend_vendor_icons_chainmail_boots_png},
    {"/vendor/icons/chainmail_chestplate.png", "image/png", besq::data::frontend_vendor_icons_chainmail_chestplate_png},
    {"/vendor/icons/chainmail_helmet.png", "image/png", besq::data::frontend_vendor_icons_chainmail_helmet_png},
    {"/vendor/icons/chainmail_leggings.png", "image/png", besq::data::frontend_vendor_icons_chainmail_leggings_png},
    {"/vendor/icons/copper_axe.png", "image/png", besq::data::frontend_vendor_icons_copper_axe_png},
    {"/vendor/icons/copper_boots.png", "image/png", besq::data::frontend_vendor_icons_copper_boots_png},
    {"/vendor/icons/copper_chestplate.png", "image/png", besq::data::frontend_vendor_icons_copper_chestplate_png},
    {"/vendor/icons/copper_helmet.png", "image/png", besq::data::frontend_vendor_icons_copper_helmet_png},
    {"/vendor/icons/copper_hoe.png", "image/png", besq::data::frontend_vendor_icons_copper_hoe_png},
    {"/vendor/icons/copper_leggings.png", "image/png", besq::data::frontend_vendor_icons_copper_leggings_png},
    {"/vendor/icons/copper_pickaxe.png", "image/png", besq::data::frontend_vendor_icons_copper_pickaxe_png},
    {"/vendor/icons/copper_shovel.png", "image/png", besq::data::frontend_vendor_icons_copper_shovel_png},
    {"/vendor/icons/copper_spear.png", "image/png", besq::data::frontend_vendor_icons_copper_spear_png},
    {"/vendor/icons/copper_sword.png", "image/png", besq::data::frontend_vendor_icons_copper_sword_png},
    {"/vendor/icons/crossbow.png", "image/png", besq::data::frontend_vendor_icons_crossbow_png},
    {"/vendor/icons/diamond_axe.png", "image/png", besq::data::frontend_vendor_icons_diamond_axe_png},
    {"/vendor/icons/diamond_boots.png", "image/png", besq::data::frontend_vendor_icons_diamond_boots_png},
    {"/vendor/icons/diamond_chestplate.png", "image/png", besq::data::frontend_vendor_icons_diamond_chestplate_png},
    {"/vendor/icons/diamond_helmet.png", "image/png", besq::data::frontend_vendor_icons_diamond_helmet_png},
    {"/vendor/icons/diamond_hoe.png", "image/png", besq::data::frontend_vendor_icons_diamond_hoe_png},
    {"/vendor/icons/diamond_leggings.png", "image/png", besq::data::frontend_vendor_icons_diamond_leggings_png},
    {"/vendor/icons/diamond_pickaxe.png", "image/png", besq::data::frontend_vendor_icons_diamond_pickaxe_png},
    {"/vendor/icons/diamond_shovel.png", "image/png", besq::data::frontend_vendor_icons_diamond_shovel_png},
    {"/vendor/icons/diamond_spear.png", "image/png", besq::data::frontend_vendor_icons_diamond_spear_png},
    {"/vendor/icons/diamond_sword.png", "image/png", besq::data::frontend_vendor_icons_diamond_sword_png},
    {"/vendor/icons/elytra.png", "image/png", besq::data::frontend_vendor_icons_elytra_png},
    {"/vendor/icons/enchanted_book.png", "image/png", besq::data::frontend_vendor_icons_enchanted_book_png},
    {"/vendor/icons/fishing_rod.png", "image/png", besq::data::frontend_vendor_icons_fishing_rod_png},
    {"/vendor/icons/flint_and_steel.png", "image/png", besq::data::frontend_vendor_icons_flint_and_steel_png},
    {"/vendor/icons/golden_axe.png", "image/png", besq::data::frontend_vendor_icons_golden_axe_png},
    {"/vendor/icons/golden_boots.png", "image/png", besq::data::frontend_vendor_icons_golden_boots_png},
    {"/vendor/icons/golden_chestplate.png", "image/png", besq::data::frontend_vendor_icons_golden_chestplate_png},
    {"/vendor/icons/golden_helmet.png", "image/png", besq::data::frontend_vendor_icons_golden_helmet_png},
    {"/vendor/icons/golden_hoe.png", "image/png", besq::data::frontend_vendor_icons_golden_hoe_png},
    {"/vendor/icons/golden_leggings.png", "image/png", besq::data::frontend_vendor_icons_golden_leggings_png},
    {"/vendor/icons/golden_pickaxe.png", "image/png", besq::data::frontend_vendor_icons_golden_pickaxe_png},
    {"/vendor/icons/golden_shovel.png", "image/png", besq::data::frontend_vendor_icons_golden_shovel_png},
    {"/vendor/icons/golden_spear.png", "image/png", besq::data::frontend_vendor_icons_golden_spear_png},
    {"/vendor/icons/golden_sword.png", "image/png", besq::data::frontend_vendor_icons_golden_sword_png},
    {"/vendor/icons/iron_axe.png", "image/png", besq::data::frontend_vendor_icons_iron_axe_png},
    {"/vendor/icons/iron_boots.png", "image/png", besq::data::frontend_vendor_icons_iron_boots_png},
    {"/vendor/icons/iron_chestplate.png", "image/png", besq::data::frontend_vendor_icons_iron_chestplate_png},
    {"/vendor/icons/iron_helmet.png", "image/png", besq::data::frontend_vendor_icons_iron_helmet_png},
    {"/vendor/icons/iron_hoe.png", "image/png", besq::data::frontend_vendor_icons_iron_hoe_png},
    {"/vendor/icons/iron_leggings.png", "image/png", besq::data::frontend_vendor_icons_iron_leggings_png},
    {"/vendor/icons/iron_pickaxe.png", "image/png", besq::data::frontend_vendor_icons_iron_pickaxe_png},
    {"/vendor/icons/iron_shovel.png", "image/png", besq::data::frontend_vendor_icons_iron_shovel_png},
    {"/vendor/icons/iron_spear.png", "image/png", besq::data::frontend_vendor_icons_iron_spear_png},
    {"/vendor/icons/iron_sword.png", "image/png", besq::data::frontend_vendor_icons_iron_sword_png},
    {"/vendor/icons/leather_boots.png", "image/png", besq::data::frontend_vendor_icons_leather_boots_png},
    {"/vendor/icons/leather_chestplate.png", "image/png", besq::data::frontend_vendor_icons_leather_chestplate_png},
    {"/vendor/icons/leather_helmet.png", "image/png", besq::data::frontend_vendor_icons_leather_helmet_png},
    {"/vendor/icons/leather_leggings.png", "image/png", besq::data::frontend_vendor_icons_leather_leggings_png},
    {"/vendor/icons/mace.png", "image/png", besq::data::frontend_vendor_icons_mace_png},
    {"/vendor/icons/misc.png", "image/png", besq::data::frontend_vendor_icons_misc_png},
    {"/vendor/icons/netherite_axe.png", "image/png", besq::data::frontend_vendor_icons_netherite_axe_png},
    {"/vendor/icons/netherite_boots.png", "image/png", besq::data::frontend_vendor_icons_netherite_boots_png},
    {"/vendor/icons/netherite_chestplate.png", "image/png", besq::data::frontend_vendor_icons_netherite_chestplate_png},
    {"/vendor/icons/netherite_helmet.png", "image/png", besq::data::frontend_vendor_icons_netherite_helmet_png},
    {"/vendor/icons/netherite_hoe.png", "image/png", besq::data::frontend_vendor_icons_netherite_hoe_png},
    {"/vendor/icons/netherite_leggings.png", "image/png", besq::data::frontend_vendor_icons_netherite_leggings_png},
    {"/vendor/icons/netherite_pickaxe.png", "image/png", besq::data::frontend_vendor_icons_netherite_pickaxe_png},
    {"/vendor/icons/netherite_shovel.png", "image/png", besq::data::frontend_vendor_icons_netherite_shovel_png},
    {"/vendor/icons/netherite_spear.png", "image/png", besq::data::frontend_vendor_icons_netherite_spear_png},
    {"/vendor/icons/netherite_sword.png", "image/png", besq::data::frontend_vendor_icons_netherite_sword_png},
    {"/vendor/icons/shears.png", "image/png", besq::data::frontend_vendor_icons_shears_png},
    {"/vendor/icons/shield.png", "image/png", besq::data::frontend_vendor_icons_shield_png},
    {"/vendor/icons/stone_axe.png", "image/png", besq::data::frontend_vendor_icons_stone_axe_png},
    {"/vendor/icons/stone_hoe.png", "image/png", besq::data::frontend_vendor_icons_stone_hoe_png},
    {"/vendor/icons/stone_pickaxe.png", "image/png", besq::data::frontend_vendor_icons_stone_pickaxe_png},
    {"/vendor/icons/stone_shovel.png", "image/png", besq::data::frontend_vendor_icons_stone_shovel_png},
    {"/vendor/icons/stone_spear.png", "image/png", besq::data::frontend_vendor_icons_stone_spear_png},
    {"/vendor/icons/stone_sword.png", "image/png", besq::data::frontend_vendor_icons_stone_sword_png},
    {"/vendor/icons/trident.png", "image/png", besq::data::frontend_vendor_icons_trident_png},
    {"/vendor/icons/turtle_helmet.png", "image/png", besq::data::frontend_vendor_icons_turtle_helmet_png},
    {"/vendor/icons/turtle_shell.png", "image/png", besq::data::frontend_vendor_icons_turtle_shell_png},
    {"/vendor/icons/warped_fungus_on_a_stick.png", "image/png", besq::data::frontend_vendor_icons_warped_fungus_on_a_stick_png},
    {"/vendor/icons/wooden_axe.png", "image/png", besq::data::frontend_vendor_icons_wooden_axe_png},
    {"/vendor/icons/wooden_hoe.png", "image/png", besq::data::frontend_vendor_icons_wooden_hoe_png},
    {"/vendor/icons/wooden_pickaxe.png", "image/png", besq::data::frontend_vendor_icons_wooden_pickaxe_png},
    {"/vendor/icons/wooden_shovel.png", "image/png", besq::data::frontend_vendor_icons_wooden_shovel_png},
    {"/vendor/icons/wooden_spear.png", "image/png", besq::data::frontend_vendor_icons_wooden_spear_png},
    {"/vendor/icons/wooden_sword.png", "image/png", besq::data::frontend_vendor_icons_wooden_sword_png},
    {"/vendor/icons/sprite.png", "image/png", besq::data::frontend_vendor_icons_sprite_png},
    {"/vendor/mdui/mdui.css", "text/css", besq::data::frontend_vendor_mdui_mdui_css},
    {"/vendor/mdui/mdui.global.js", "text/javascript", besq::data::frontend_vendor_mdui_mdui_global_js},
    {"/views/calculator.js", "text/javascript", besq::data::frontend_view_calculator},
    {"/views/profiles.js", "text/javascript", besq::data::frontend_view_profiles},
    {"/views/algorithms.js", "text/javascript", besq::data::frontend_view_algorithms},
    {"/views/history.js", "text/javascript", besq::data::frontend_view_history},
    {"/views/settings.js", "text/javascript", besq::data::frontend_view_settings},
    {"/views/status.js", "text/javascript", besq::data::frontend_view_status},
    {"/views/pager.js", "text/javascript", besq::data::frontend_view_pager},
};

/// Build the static-resource table. When `frontend_dir` is non-empty (dev
/// mode --frontend-dir), read files from disk for hot reload; otherwise use
/// the embedded copies.
static std::map<std::string, web::StaticResource> build_static(const std::string& frontend_dir) {
    std::map<std::string, web::StaticResource> m;
    for (const auto& a : kAssets) {
        if (!frontend_dir.empty()) {
            auto disk = std::filesystem::path(frontend_dir) / std::string(a.url).substr(1);
            if (std::filesystem::exists(disk)) {
                m[a.url] = web::StaticResource{a.type, read_file(disk.string())};
                continue;
            }
        }
        m[a.url] = web::StaticResource{a.type, std::string(a.embed())};
    }
    return m;
}

/// Directory containing the current executable (best-effort; "" if unknown).
static std::string current_exe_dir() {
#if defined(__linux__)
    char buf[4096];
    ssize_t n = ::readlink("/proc/self/exe", buf, sizeof(buf) - 1);
    if (n <= 0)
        return {};
    buf[n] = '\0';
    return std::filesystem::path(buf).parent_path().string();
#elif defined(_WIN32)
    char buf[MAX_PATH];
    DWORD n = ::GetModuleFileNameA(nullptr, buf, MAX_PATH);
    if (n == 0)
        return {};
    return std::filesystem::path(buf).parent_path().string();
#else
    return {};
#endif
}

/// /public 磁盘根（可选，dev 模式）。解析序：cfg.gui_res_dir（来自
/// BESQ_GUI_RES_DIR，"" 时跳过）→ ./res → <exe_dir>/res；都不存在 → 空（跳过挂载）。
static std::filesystem::path resolve_res_dir(const std::string& res_dir) {
    if (!res_dir.empty() && std::filesystem::is_directory(res_dir))
        return std::filesystem::path(res_dir);
    if (std::filesystem::is_directory("./res"))
        return std::filesystem::path("./res");
    const std::string dir = current_exe_dir();
    if (!dir.empty()) {
        auto candidate = std::filesystem::path(dir) / "res";
        if (std::filesystem::is_directory(candidate))
            return candidate;
    }
    return {};
}

int main(int argc, char* argv[]) try {
    auto& cfg = AppConfig::get();
    register_builtin_translations(LanguageManager::instance());
    // 持久化语言（config.json / BESQ_LANG，env > config > 默认）在 PATCH 之外
    // 启动即生效；未知 code 由 select() 回退 en_US。
    if (!cfg.runtime_lang.empty())
        LanguageManager::instance().select(cfg.runtime_lang);
    // GUI 进程覆盖 console 阈值到 Info：启动/关闭/错误进 console 可见；DEBUG
    // 行只进文件（FileConsumer 按文件阈值门控）不刷 console。仅此进程覆盖，
    // CLI 不受影响（CLAUDE.md 的 json/compact 机器输出保护）。
    cfg.log_console_level = 1;
    setup_logger(cfg.logger_config());

    bool open_browser = cfg.gui_open_browser;
    std::string frontend_dir; // --frontend-dir (dev hot reload)
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "--help" || a == "-h") {
            std::cout << "besq-gui — BestEnchSeq Web GUI\n"
                      << "Usage: besq-gui [--browser] [--frontend-dir DIR]\n"
                      << "  --browser           open the default browser (the v1 host)\n"
                      << "  --frontend-dir DIR  serve the SPA from DIR (dev hot-reload)\n"
                      << "Environment: BESQ_GUI_HOST, BESQ_GUI_PORT, BESQ_GUI_OPEN_BROWSER\n"
                      << "             BESQ_GUI_WORKERS (consumer threads, default 2)\n"
                      << "             BESQ_GUI_RES_DIR (optional /public disk root)\n"
                      << "             BESQ_LANG (language; config.json lang otherwise)\n"
                      << "Runtime settings (lang/log_level/log_console/log_console_level) are\n"
                      << "persisted to <cwd>/config.json by PATCH /api/settings and reloaded\n"
                      << "at startup (env vars still win: env > config.json > default)\n";
            return 0;
        }
        if (a == "--version" || a == "-V") {
            std::cout << "besq-gui " << BESQ_VERSION << "\n";
            return 0;
        }
        if (a == "--browser")
            open_browser = true;
        else if (a == "--frontend-dir" && i + 1 < argc)
            frontend_dir = argv[++i];
    }

    BesqContext ctx;
    ctx.load_builtin();
    ctx.load_profiles();

    // WebModule 做全部路由（/health, /api/*, /public 静态 + SSE），HTTP 服务器只负责
    // 字节 ↔ dispatch 桥接。dispatch 结果原样返回，避免 HttpResponse::json 重包装把
    // SPA 的 text/html 资产强制成 application/json。
    //
    // 关机顺序依赖：server 先声明 → 逆序析构时 module 先死，其 hub.clear() 先于
    // Reactor（server 所有）释放执行。SseHub 订阅共享持有 Connection，帧汇捕获裸
    // Reactor*；若 Reactor 先于 hub.clear() 释放，任何日志/任务帧 publish 都会调用
    // 已析构 Reactor 的 loop → UAF。hub 订阅的生命周期必须短于 Reactor。
    web::HttpServer server;

    web::WebModule module(ctx);
    module.set_static_resources(build_static(frontend_dir));
    auto res_dir = resolve_res_dir(cfg.gui_res_dir);
    if (!res_dir.empty())
        module.mount_res_dir(res_dir);

    // fallback 仅在 server 存活期内被调用；module 声明在后（后析构），引用始终有效。
    server.set_fallback([&](const web::HttpRequest& r) { return module.dispatch(r); });

    // 限流（默认关闭；GUI 显式开启，本地宽松阈值）。部署经 Nginx 前置时：
    // rl.client_addr_policy.trust_forwarded = true;（对端恒为 nginx）
    web::RateLimitConfig rl;
    rl.enabled = true;
    server.use(web::make_rate_limiter(rl));
    // 访问日志默认开启（Combined 格式，INFO 级，见 AccessLog.h）。

    if (!server.start(cfg.gui_host, cfg.gui_port, cfg.gui_workers)) {
        LOG_ERROR("failed to bind %s:%u", cfg.gui_host.c_str(), static_cast<unsigned>(cfg.gui_port));
        std::cerr << "besq-gui: failed to bind " << cfg.gui_host << ":" << cfg.gui_port << "\n";
        return 1;
    }

    const auto url = "http://" + cfg.gui_host + ":" + std::to_string(server.port()) + "/";
    LOG_INFO("besq-gui listening at %s", url.c_str());
    std::cout << "besq-gui serving at " << url << "\n";

    // v1 host: the default browser. A native WebView2 window (src/gui/
    // webview_host.*) is future work — it needs the Microsoft WebView2 SDK,
    // which is not vendored. `server.run()` keeps serving on this thread for
    // the process lifetime; Ctrl+C exits.
    if (open_browser) {
#ifdef _WIN32
        std::string cmd = "start \"\" \"" + url + "\"";
        std::system(cmd.c_str());
#else
        std::string cmd = "xdg-open " + url + " >/dev/null 2>&1 &";
        std::system(cmd.c_str());
#endif
    }

    server.run();
    LOG_INFO("server shutting down");
    besq::log::flush();
    return 0;

} catch (const std::exception& e) {
    std::cerr << "besq-gui: " << e.what() << std::endl;
    return 1;
}
