#include "AppConfig.h"
#include "builtin/I18nLoader.h"
#include "common/i18n/Language.h"
#include "common/log/log.hpp"
#include "common/log/LogRingBuffer.h"
#include "domain/interface/BesqContext.h"
#include "domain/interface/web/WebModule.h"
#include "domain/interface/web/http/HttpServer.h"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <memory>
#include <string>
#include <thread>

namespace besq::data {
// Embedded frontend assets (generated by embed_resource).
std::string_view frontend_index_html();
std::string_view frontend_styles_css();
std::string_view frontend_app_js();
std::string_view frontend_api_js();
std::string_view frontend_i18n_js();
std::string_view frontend_view_calculator();
std::string_view frontend_view_profiles();
std::string_view frontend_view_algorithms();
std::string_view frontend_view_logs();
std::string_view frontend_view_settings();
std::string_view frontend_view_status();
} // namespace besq::data

static std::string read_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    return std::string((std::istreambuf_iterator<char>(f)),
                       std::istreambuf_iterator<char>());
}

/// Build the static-resource table. When `frontend_dir` is non-empty (dev
/// mode --frontend-dir), read files from disk for hot reload; otherwise use
/// the embedded copies.
static std::map<std::string, webhttp::StaticResource> build_static(const std::string& frontend_dir) {
    using webhttp::StaticResource;
    std::map<std::string, StaticResource> m;
    const std::vector<std::pair<std::string, std::string>> files = {
        {"/index.html", "text/html"}, {"/styles.css", "text/css"},
        {"/app.js", "text/javascript"}, {"/api.js", "text/javascript"},
        {"/i18n.js", "text/javascript"},
        {"/views/calculator.js", "text/javascript"},
        {"/views/profiles.js", "text/javascript"},
        {"/views/algorithms.js", "text/javascript"},
        {"/views/logs.js", "text/javascript"},
        {"/views/settings.js", "text/javascript"},
        {"/views/status.js", "text/javascript"},
    };
    const std::vector<std::string> embedded = {
        std::string(besq::data::frontend_index_html()),
        std::string(besq::data::frontend_styles_css()),
        std::string(besq::data::frontend_app_js()),
        std::string(besq::data::frontend_api_js()),
        std::string(besq::data::frontend_i18n_js()),
        std::string(besq::data::frontend_view_calculator()),
        std::string(besq::data::frontend_view_profiles()),
        std::string(besq::data::frontend_view_algorithms()),
        std::string(besq::data::frontend_view_logs()),
        std::string(besq::data::frontend_view_settings()),
        std::string(besq::data::frontend_view_status()),
    };
    for (size_t i = 0; i < files.size(); ++i) {
        if (!frontend_dir.empty()) {
            auto disk = std::filesystem::path(frontend_dir) /
                        (files[i].first == "/index.html" ? "index.html" : files[i].first.substr(1));
            if (std::filesystem::exists(disk)) {
                m[files[i].first] = StaticResource{files[i].second, read_file(disk.string())};
                continue;
            }
        }
        m[files[i].first] = StaticResource{files[i].second, embedded[i]};
    }
    return m;
}

int main(int argc, char* argv[]) try {
    auto& cfg = AppConfig::get();
    register_builtin_translations(LanguageManager::instance());
    setup_logger(cfg.logger_config());

    bool open_browser = cfg.gui_open_browser;
    std::string frontend_dir;   // --frontend-dir (dev hot reload)
    for (int i = 1; i < argc; ++i) {
        if (std::string(argv[i]) == "--browser") open_browser = true;
        else if (std::string(argv[i]) == "--frontend-dir" && i + 1 < argc)
            frontend_dir = argv[++i];
    }

    BesqContext ctx;
    ctx.load_builtin();
    ctx.load_profiles();

    // Ring buffer for /api/logs.
    auto ring = std::make_shared<LogRingBuffer>(1024);
    Logger::instance().set_ring_buffer(ring);

    webhttp::WebModule module(ctx);
    module.set_static_resources(build_static(frontend_dir));

    // WebModule does all routing (/health, /api/*, static assets); the HTTP
    // server just bridges bytes ↔ dispatch. Same wiring as test_web_integration.
    // Dispatch DIRECTLY — re-wrapping with HttpResponse::json would force
    // content_type application/json and break the SPA's text/html assets.
    webhttp::HttpServer server;
    server.set_fallback([&](const webhttp::HttpRequest& r) {
        return module.dispatch(r.method, r.path, r.body);
    });

    if (!server.start(cfg.gui_host, cfg.gui_port)) {
        std::cerr << "besq-gui: failed to bind " << cfg.gui_host << ":" << cfg.gui_port << "\n";
        return 1;
    }

    const auto url = "http://" + cfg.gui_host + ":" + std::to_string(server.port()) + "/";
    std::cout << "besq-gui serving at " << url << "\n";

    if (open_browser) {
#ifdef _WIN32
        std::string cmd = "start \"\" \"" + url + "\"";
        std::system(cmd.c_str());
#else
        std::string cmd = "xdg-open " + url + " >/dev/null 2>&1 &";
        std::system(cmd.c_str());
#endif
    }

    // WebView2 host lands in M4. Until then, serve on this thread.
    server.run();
    return 0;

} catch (const std::exception& e) {
    std::cerr << "besq-gui: " << e.what() << std::endl;
    return 1;
}
