#!/usr/bin/env python3
"""Regenerate the item-icon sprite sheet + frontend tile index.

Sources:  assets/item_icons/*.png   (16x16 RGBA, one per item id)
Outputs:  gui/frontend/vendor/icons/sprite.png   (10-col tile grid)
          gui/frontend/sprite.js                 (tile index, generated)

Layout contract (consumed by sprite.js at runtime — must not drift):
  10 cols x ceil(N/10) rows of 16px tiles; ids sorted ascending;
  tile index = row * 10 + col.  Sheet and index are written from the
  same sorted order so iconIndex() stays in sync.

Run from the project root:
  python3 scripts/gen_sprite.py
"""

import os
import sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "assets", "item_icons")
SHEET_PATH = os.path.join(ROOT, "gui", "frontend", "vendor", "icons", "sprite.png")
INDEX_PATH = os.path.join(ROOT, "gui", "frontend", "sprite.js")

TILE = 16
COLS = 10


def load_tiles():
    ids = sorted(os.listdir(SRC_DIR))
    tiles = []
    for name in ids:
        if not name.endswith(".png"):
            continue
        img = Image.open(os.path.join(SRC_DIR, name))
        if img.size != (TILE, TILE):
            sys.exit(f"error: {name} is {img.size}, expected {TILE}x{TILE}")
        tiles.append((name[: -len(".png")], img.convert("RGBA")))
    return tiles


def build_sheet(tiles):
    rows = (len(tiles) + COLS - 1) // COLS
    sheet = Image.new("RGBA", (COLS * TILE, rows * TILE), (0, 0, 0, 0))
    for i, (_, img) in enumerate(tiles):
        sheet.paste(img, ((i % COLS) * TILE, (i // COLS) * TILE))
    return sheet


def build_index(tiles, rows):
    ids = ", ".join(f'"{tid}"' for tid, _ in tiles)
    return f"""\
// GENERATED by scripts/gen_sprite.py — DO NOT EDIT BY HAND.
// Sheet: gui/frontend/vendor/icons/sprite.png, {COLS} cols × {rows} rows of
// {TILE}px tiles; ids sorted, tile index = row * {COLS} + col. The generator
// writes sheet and index from the same order so iconIndex() stays in sync.
export const SPRITE_URL = '/public/vendor/icons/sprite.png';
export const ICON_SIZE = {TILE};
export const ICON_COLS = {COLS};

const ICON_IDS = [{ids}];

// Tile index for an id ('minecraft:' prefix stripped); -1 when the id is
// absent from the sheet (modded) — callers render no icon.
export function iconIndex(id) {{
  let s = String(id || '');
  if (s.startsWith('minecraft:')) s = s.slice('minecraft:'.length);
  return ICON_IDS.indexOf(s);
}}

// Inline background style for a DOM icon box of `px` display size, or null
// when the id has no tile. background-size scales the sheet so the {TILE}px
// tile fills the box exactly (same fill semantics as the old per-id <img>).
export function iconStyle(id, px = 20) {{
  const i = iconIndex(id);
  if (i < 0) return null;
  const col = i % ICON_COLS;
  const row = (i / ICON_COLS) | 0;
  const rows = Math.ceil(ICON_IDS.length / ICON_COLS);
  return `background-image:url(${{SPRITE_URL}});` +
    `background-size:${{ICON_COLS * px}}px ${{rows * px}}px;` +
    `background-position:${{-col * px}}px ${{-row * px}}px;` +
    `background-repeat:no-repeat;`;
}}

// HTML for a sprite-tile span ('' when the id is not in the sheet, matching
// the old onerror-hidden <img>). `title` must already be escaped by the
// caller; `extraStyle` is caller-authored CSS, never user data.
export function iconSpanHtml(id, px = 20, title = '', extraStyle = '') {{
  const st = iconStyle(id, px);
  if (!st) return '';
  return `<span class="icon-sprite" style="width:${{px}}px;height:${{px}}px;${{st}}${{extraStyle}}"` +
    (title ? ` title="${{title}}"` : '') + `></span>`;
}}
"""


def main():
    tiles = load_tiles()
    if not tiles:
        sys.exit(f"error: no source icons in {SRC_DIR}")
    rows = (len(tiles) + COLS - 1) // COLS
    build_sheet(tiles).save(SHEET_PATH)
    # 统一 LF 行尾（.gitattributes: * text=auto eol=lf）。
    with open(INDEX_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(build_index(tiles, rows))
    print(f"wrote {SHEET_PATH} ({len(tiles)} tiles, {COLS}x{rows})")
    print(f"wrote {INDEX_PATH}")


if __name__ == "__main__":
    main()
