// names_zh.js — vanilla id → 中文名映射。
// 生成自 data/i18n/minecraft/zh_CN.json（官方 zh_cn locale，MC 26.2）+
// data/builtin/vanilla.json 的 id 全集；脚本 scripts/gen_names_zh.py 可再生。
// displayName() 是统一入口：zh-CN 下查表，其余语言回落 fallback。
import { langCode } from './i18n.js';

const NAME_ZH = {
  "aqua_affinity": "水下速掘",
  "bane_of_arthropods": "节肢杀手",
  "binding_curse": "绑定诅咒",
  "blast_protection": "爆炸保护",
  "bow": "弓",
  "breach": "破甲",
  "brush": "刷子",
  "carrot_on_a_stick": "胡萝卜钓竿",
  "chainmail_boots": "锁链靴子",
  "chainmail_chestplate": "锁链胸甲",
  "chainmail_helmet": "锁链头盔",
  "chainmail_leggings": "锁链护腿",
  "channeling": "引雷",
  "copper_axe": "铜斧",
  "copper_boots": "铜靴子",
  "copper_chestplate": "铜胸甲",
  "copper_helmet": "铜头盔",
  "copper_hoe": "铜锄",
  "copper_leggings": "铜护腿",
  "copper_pickaxe": "铜镐",
  "copper_shovel": "铜锹",
  "copper_spear": "铜矛",
  "copper_sword": "铜剑",
  "crossbow": "弩",
  "density": "致密",
  "depth_strider": "深海探索者",
  "diamond_axe": "钻石斧",
  "diamond_boots": "钻石靴子",
  "diamond_chestplate": "钻石胸甲",
  "diamond_helmet": "钻石头盔",
  "diamond_hoe": "钻石锄",
  "diamond_leggings": "钻石护腿",
  "diamond_pickaxe": "钻石镐",
  "diamond_shovel": "钻石锹",
  "diamond_spear": "钻石矛",
  "diamond_sword": "钻石剑",
  "efficiency": "效率",
  "elytra": "鞘翅",
  "enchanted_book": "附魔书",
  "feather_falling": "摔落缓冲",
  "fire_aspect": "火焰附加",
  "fire_protection": "火焰保护",
  "fishing_rod": "钓鱼竿",
  "flame": "火矢",
  "flint_and_steel": "打火石",
  "fortune": "时运",
  "frost_walker": "冰霜行者",
  "golden_axe": "金斧",
  "golden_boots": "金靴子",
  "golden_chestplate": "金胸甲",
  "golden_helmet": "金头盔",
  "golden_hoe": "金锄",
  "golden_leggings": "金护腿",
  "golden_pickaxe": "金镐",
  "golden_shovel": "金锹",
  "golden_spear": "金矛",
  "golden_sword": "金剑",
  "impaling": "穿刺",
  "infinity": "无限",
  "iron_axe": "铁斧",
  "iron_boots": "铁靴子",
  "iron_chestplate": "铁胸甲",
  "iron_helmet": "铁头盔",
  "iron_hoe": "铁锄",
  "iron_leggings": "铁护腿",
  "iron_pickaxe": "铁镐",
  "iron_shovel": "铁锹",
  "iron_spear": "铁矛",
  "iron_sword": "铁剑",
  "knockback": "击退",
  "leather_boots": "皮革靴子",
  "leather_chestplate": "皮革外套",
  "leather_helmet": "皮革帽子",
  "leather_leggings": "皮革裤子",
  "looting": "抢夺",
  "loyalty": "忠诚",
  "luck_of_the_sea": "海之眷顾",
  "lunge": "突进",
  "lure": "饵钓",
  "mace": "重锤",
  "mending": "经验修补",
  "misc": "杂项",
  "multishot": "多重射击",
  "netherite_axe": "下界合金斧",
  "netherite_boots": "下界合金靴子",
  "netherite_chestplate": "下界合金胸甲",
  "netherite_helmet": "下界合金头盔",
  "netherite_hoe": "下界合金锄",
  "netherite_leggings": "下界合金护腿",
  "netherite_pickaxe": "下界合金镐",
  "netherite_shovel": "下界合金锹",
  "netherite_spear": "下界合金矛",
  "netherite_sword": "下界合金剑",
  "piercing": "穿透",
  "power": "力量",
  "projectile_protection": "弹射物保护",
  "protection": "保护",
  "punch": "冲击",
  "quick_charge": "快速装填",
  "respiration": "水下呼吸",
  "riptide": "激流",
  "sharpness": "锋利",
  "shears": "剪刀",
  "shield": "盾牌",
  "silk_touch": "精准采集",
  "smite": "亡灵杀手",
  "soul_speed": "灵魂疾行",
  "stone_axe": "石斧",
  "stone_hoe": "石锄",
  "stone_pickaxe": "石镐",
  "stone_shovel": "石锹",
  "stone_spear": "石矛",
  "stone_sword": "石剑",
  "sweeping_edge": "横扫之刃",
  "swift_sneak": "迅捷潜行",
  "thorns": "荆棘",
  "trident": "三叉戟",
  "turtle_helmet": "海龟壳",
  "turtle_shell": "海龟壳",
  "unbreaking": "耐久",
  "vanishing_curse": "消失诅咒",
  "warped_fungus_on_a_stick": "诡异菌钓竿",
  "wind_burst": "风爆",
  "wooden_axe": "木斧",
  "wooden_hoe": "木锄",
  "wooden_pickaxe": "木镐",
  "wooden_shovel": "木锹",
  "wooden_spear": "木矛",
  "wooden_sword": "木剑",
};

// 统一显示名入口：id 可为 NSID（minecraft:sharpness）、标签
// （#minecraft:head_armor）或短 id（sharpness）；非 vanilla id 回落
// fallback（后端下发的英文名 / 原文）。
export function displayName(id, fallback) {
  if (langCode() !== 'zh-CN') return fallback || String(id || '');
  const key = String(id || '').replace(/^#?minecraft:/, '').replace(/^#/, '');
  return NAME_ZH[key] || fallback || String(id || '');
}
