// GENERATED by scripts/gen_sprite.py — DO NOT EDIT BY HAND.
// Sheet: gui/frontend/vendor/icons/sprite.png, 10 cols × 9 rows of
// 16px tiles; ids sorted, tile index = row * 10 + col. The generator
// writes sheet and index from the same order so iconIndex() stays in sync.
export const SPRITE_URL = '/public/vendor/icons/sprite.png';
export const ICON_SIZE = 16;
export const ICON_COLS = 10;

const ICON_IDS = ["bow", "brush", "carrot_on_a_stick", "chainmail_boots", "chainmail_chestplate", "chainmail_helmet", "chainmail_leggings", "copper_axe", "copper_boots", "copper_chestplate", "copper_helmet", "copper_hoe", "copper_leggings", "copper_pickaxe", "copper_shovel", "copper_spear", "copper_sword", "crossbow", "diamond_axe", "diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_hoe", "diamond_leggings", "diamond_pickaxe", "diamond_shovel", "diamond_spear", "diamond_sword", "elytra", "enchanted_book", "fishing_rod", "flint_and_steel", "golden_axe", "golden_boots", "golden_chestplate", "golden_helmet", "golden_hoe", "golden_leggings", "golden_pickaxe", "golden_shovel", "golden_spear", "golden_sword", "iron_axe", "iron_boots", "iron_chestplate", "iron_helmet", "iron_hoe", "iron_leggings", "iron_pickaxe", "iron_shovel", "iron_spear", "iron_sword", "leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings", "mace", "misc", "netherite_axe", "netherite_boots", "netherite_chestplate", "netherite_helmet", "netherite_hoe", "netherite_leggings", "netherite_pickaxe", "netherite_shovel", "netherite_spear", "netherite_sword", "shears", "shield", "stone_axe", "stone_hoe", "stone_pickaxe", "stone_shovel", "stone_spear", "stone_sword", "trident", "turtle_helmet", "turtle_shell", "warped_fungus_on_a_stick", "wooden_axe", "wooden_hoe", "wooden_pickaxe", "wooden_shovel", "wooden_spear", "wooden_sword"];

// Tile index for an id ('minecraft:' prefix stripped); -1 when the id is
// absent from the sheet (modded) — callers render no icon.
export function iconIndex(id) {
  let s = String(id || '');
  if (s.startsWith('minecraft:')) s = s.slice('minecraft:'.length);
  return ICON_IDS.indexOf(s);
}

// Inline background style for a DOM icon box of `px` display size, or null
// when the id has no tile. background-size scales the sheet so the 16px
// tile fills the box exactly (same fill semantics as the old per-id <img>).
export function iconStyle(id, px = 20) {
  const i = iconIndex(id);
  if (i < 0) return null;
  const col = i % ICON_COLS;
  const row = (i / ICON_COLS) | 0;
  const rows = Math.ceil(ICON_IDS.length / ICON_COLS);
  return `background-image:url(${SPRITE_URL});` +
    `background-size:${ICON_COLS * px}px ${rows * px}px;` +
    `background-position:${-col * px}px ${-row * px}px;` +
    `background-repeat:no-repeat;`;
}

// HTML for a sprite-tile span ('' when the id is not in the sheet, matching
// the old onerror-hidden <img>). `title` must already be escaped by the
// caller; `extraStyle` is caller-authored CSS, never user data.
export function iconSpanHtml(id, px = 20, title = '', extraStyle = '') {
  const st = iconStyle(id, px);
  if (!st) return '';
  return `<span class="icon-sprite" style="width:${px}px;height:${px}px;${st}${extraStyle}"` +
    (title ? ` title="${title}"` : '') + `></span>`;
}
