# ═══════════════════════════════════════════════════════════════════════════════
# Generate besq-coreConfig.cmake — used by the plugin build system
#
# Plugins consume this via:
#   cmake -S plugins -B build/plugins -DBESQ_CORE_DIR=<host-build-dir>
#
# Requires: CMAKE_BINARY_DIR, WIN32/UNIX context, BESQ_MAX_SOLUTIONS
# ═══════════════════════════════════════════════════════════════════════════════

function(generate_besq_core_config)
    if(WIN32)
        # Windows (MinGW/Clang): DLL doesn't auto-export symbols from linked
        # static libs, so plugins must link the static libs directly.
        set(_import
"# Windows: link static libs directly (DLL export does not cover static deps)
set(_besq_static_libs
    \"\${_besq_build}/src/common/besq-common-core.lib\"
    \"\${_besq_build}/src/common/besq-common-io.lib\"
    \"\${_besq_build}/src/common/besq-common-log.lib\"
    \"\${_besq_build}/src/common/besq-common-i18n.lib\"
    \"\${_besq_build}/src/common/besq-common-cli.lib\"
    \"\${_besq_build}/src/domain/algorithm/besq-domain-algorithm.lib\"
    \"\${_besq_build}/src/domain/business/besq-domain-business.lib\"
    \"\${_besq_build}/src/domain/orchestration/besq-domain-orchestration.lib\"
    \"\${_besq_build}/src/domain/interface/besq-domain-interface.lib\"
)
add_library(besq-core::besq-core INTERFACE IMPORTED)
set_target_properties(besq-core::besq-core PROPERTIES
    INTERFACE_LINK_LIBRARIES \"\${_besq_static_libs}\"
    INTERFACE_INCLUDE_DIRECTORIES \"\${_besq_src}/src;\${_besq_build}/generated;\${_besq_src}/src/common\"
    INTERFACE_COMPILE_DEFINITIONS \"BESQ_MAX_SOLUTIONS=${BESQ_MAX_SOLUTIONS}\"
)")
    else()
        # Linux/macOS: .so exports all symbols, link directly
        set(_import
"# Linux/macOS: link shared library (all symbols exported)
add_library(besq-core::besq-core SHARED IMPORTED)
set_target_properties(besq-core::besq-core PROPERTIES
    IMPORTED_LOCATION \"\${_besq_build}/libbesq-core.so\"
    IMPORTED_SONAME \"libbesq-core.so\"
    INTERFACE_INCLUDE_DIRECTORIES \"\${_besq_src}/src;\${_besq_build}/generated;\${_besq_src}/src/common\"
    INTERFACE_COMPILE_DEFINITIONS \"BESQ_MAX_SOLUTIONS=${BESQ_MAX_SOLUTIONS}\"
)")
    endif()

    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/besq-coreConfig.cmake" CONTENT
"# Auto-generated by BestEnchSeq-Core build — do not edit.
# Plugin build: cmake -S plugins -B build/plugins -DBESQ_CORE_DIR=<build>
get_filename_component(_besq_build \"\${CMAKE_CURRENT_LIST_DIR}\" ABSOLUTE)
get_filename_component(_besq_src \"\${_besq_build}/..\" ABSOLUTE)
${_import}
")
endfunction()
