# EmbedResource.cmake
#
# embed_resource(INPUT <path> [SYMBOL <name>] [OUTPUT <cpp_file>])
#
# Reads a file and generates a C++ source that embeds its content as
# a constexpr std::array<unsigned char, N>.  Safe for arbitrary data.
#
# The generated file exposes besq::data::<SYMBOL>() -> std::string_view.
# SYMBOL defaults to the stem of INPUT (e.g. "vanilla" → "vanilla").
# OUTPUT defaults to ${PROJECT_BINARY_DIR}/generated/<SYMBOL>.cpp.

function(embed_resource)
    cmake_parse_arguments(ER "" "INPUT;SYMBOL;OUTPUT" "" ${ARGN})

    if(NOT ER_INPUT)
        message(FATAL_ERROR "embed_resource: INPUT is required")
    endif()
    if(NOT EXISTS "${ER_INPUT}")
        message(FATAL_ERROR "embed_resource: file not found: ${ER_INPUT}")
    endif()

    # Derive SYMBOL from filename if not provided
    if(NOT ER_SYMBOL)
        get_filename_component(_stem "${ER_INPUT}" NAME_WE)
        string(REGEX REPLACE "[^a-zA-Z0-9]" "_" ER_SYMBOL "${_stem}")
    endif()

    # Default OUTPUT
    if(NOT ER_OUTPUT)
        set(ER_OUTPUT "${PROJECT_BINARY_DIR}/generated/${ER_SYMBOL}.cpp")
    endif()

    # Read file as hex
    file(READ "${ER_INPUT}" _hex HEX)
    string(LENGTH "${_hex}" _hex_len)
    math(EXPR _data_len "${_hex_len} / 2")

    # Build byte-array initializer (16 bytes per line)
    string(ASCII 10 _NL)
    set(_bytes "")
    set(_i 0)
    set(_per_line 16)
    while(_i LESS _hex_len)
        set(_line "")
        set(_sep "")
        set(_j 0)
        while(_j LESS _per_line AND _i LESS _hex_len)
            string(SUBSTRING "${_hex}" ${_i} 2 _byte)
            string(APPEND _line "${_sep}0x${_byte}")
            set(_sep ", ")
            math(EXPR _i "${_i} + 2")
            math(EXPR _j "${_j} + 1")
        endwhile()
        set(_bytes "${_bytes}    ${_line},${_NL}")
    endwhile()

    # Write generated .cpp
    file(WRITE "${ER_OUTPUT}"
        "// Auto-generated by EmbedResource.cmake — do not edit.${_NL}"
        "#include <array>${_NL}"
        "#include <cstddef>${_NL}"
        "#include <string_view>${_NL}"
        "${_NL}"
        "namespace besq::data {${_NL}"
        "${_NL}"
        "static constexpr std::array<unsigned char, ${_data_len}> k${ER_SYMBOL} = {${_NL}"
        "${_bytes}"
        "};${_NL}"
        "${_NL}"
        "std::string_view ${ER_SYMBOL}() noexcept {${_NL}"
        "    return std::string_view{${_NL}"
        "        reinterpret_cast<const char*>(k${ER_SYMBOL}.data()),${_NL}"
        "        k${ER_SYMBOL}.size()${_NL}"
        "    };${_NL}"
        "}${_NL}"
        "${_NL}"
        "} // namespace besq::data${_NL}"
    )

    message(STATUS "embed_resource: ${ER_SYMBOL} (${_data_len} bytes) → ${ER_OUTPUT}")
endfunction()
