# EmbedResource_gen.cmake
#
# Called at build time by add_custom_command (see EmbedResource.cmake).
# Reads INPUT file and writes OUTPUT as a C++ embedded resource.
#
# Usage:
#   cmake -DINPUT=<path> -DOUTPUT=<path> -DSYMBOL=<name> -P EmbedResource_gen.cmake

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hex_len)
math(EXPR _data_len "${_hex_len} / 2")

string(ASCII 10 _NL)
set(_bytes "")
set(_i 0)
set(_per_line 16)
while(_i LESS _hex_len)
    set(_line "")
    set(_sep "")
    set(_j 0)
    while(_j LESS _per_line AND _i LESS _hex_len)
        string(SUBSTRING "${_hex}" ${_i} 2 _byte)
        string(APPEND _line "${_sep}0x${_byte}")
        set(_sep ", ")
        math(EXPR _i "${_i} + 2")
        math(EXPR _j "${_j} + 1")
    endwhile()
    set(_bytes "${_bytes}    ${_line},${_NL}")
endwhile()

file(WRITE "${OUTPUT}"
    "// Auto-generated by EmbedResource.cmake — do not edit.${_NL}"
    "#include <array>${_NL}"
    "#include <string_view>${_NL}"
    "${_NL}"
    "namespace besq::data {${_NL}"
    "${_NL}"
    "static constexpr std::array<unsigned char, ${_data_len}> k${SYMBOL} = {${_NL}"
    "${_bytes}"
    "};${_NL}"
    "${_NL}"
    "std::string_view ${SYMBOL}() noexcept {${_NL}"
    "    return std::string_view{${_NL}"
    "        reinterpret_cast<const char*>(k${SYMBOL}.data()),${_NL}"
    "        k${SYMBOL}.size()${_NL}"
    "    };${_NL}"
    "}${_NL}"
    "${_NL}"
    "} // namespace besq::data${_NL}"
)
